### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by sbekrin** [sergeybekrin/react-with-async-fonts#23]
* Structure readme.md with ToC
* Add more docs for css-in-js libs

**Comment by jimthedev** [comment]
This looks really cool. Would love to see / know if it works with pages lazily loaded routes using webpack import() + react-loadable.

**Comment by oyeanuj** [comment]
@sergeybekrin Thank you for putting out this library, this looks great! Couple of more suggestion for docs that would be super helpful:

1. A Demo please, so one can see the strategy in action :) I imagine the most common use would be to use it at a `body` level rather than individual component - so I am curious how best to use the library then.

2. How it works? Even a quick explanation that helps explain the how would be super helpful.

3. And to add to @jimthedev's comment above, a note about SSR usage.

**Comment by jimthedev** [comment]
@oyeanuj I can confirm it works well with react-loadable / webpack's import().

**Comment by sbekrin** [comment]
@oyeanuj @jimthedev @Remownz hey folks, I've published new release with breaking API changes and  polished docs with more examples. Let me know if anything important is missing ✌️
